name: 'Upload'
description: 'Upload to github releases'
inputs:
  github_token:
    description: 'github access token for upload artifact'
    required: true
  version:
    description: 'release version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate changelog
      uses: metcalfc/changelog-generator@v1
      id: changelog
      with:
        token: ${{ inputs.github_token }}
    - name: Upload artifact to Github releases
      uses: svenstaro/upload-release-action@v2
      with:
          file: dist/admissibility-rust*
          repo_token: ${{ inputs.github_token }}
          tag: 'v${{ inputs.version }}'
          overwrite: true
          file_glob: true
          body: ${{ steps.changelog.outputs.changelog }}