name: 'Upload'
description: 'Upload to github releases'
inputs:
  os:
    description: 'target os name'
    required: true
  github_token:
    description: 'github access token for upload artifact'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1

    - name: Determine next version
      shell: bash
      run: echo ${{ steps.version.outputs.version }}

    - name: Update Cargo.toml version
      shell: bash
      run: |
        sed -i "s/^version = .*/version = \"${{ steps.semver.outputs.VERSION }}\"/" Cargo.toml