name: 'Upload'
description: 'Upload to github releases'
inputs:
  os:
    description: 'target os name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Upload artifact to Github releases
      uses: svenstaro/release-release-action@v2
      with:
        name: binary-${{ inputs.os }}
        file: dist/admissibility-rust*
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'v${{ github.run_number }}'
        overwrite: true
        file_glob: true