name: 'Upload'
description: 'Upload to github releases'
inputs:
  github_token:
    description: 'github access token for upload artifact'
    required: true
  version:
    description: 'release version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate a changelog
      uses: orhun/git-cliff-action@v4
      id: git-cliff
      env:
        OUTPUT: CHANGELOG.md

    - name: Upload artifact to Github releases
      uses: svenstaro/upload-release-action@v2
      with:
          file: dist/admissibility-rust*
          repo_token: ${{ inputs.github_token }}
          tag: 'v${{ inputs.version }}'
          overwrite: true
          file_glob: true
          body: ${{ steps.git-cliff.outputs.content }}

    - name: Commit changelog
      if: inputs.target == 'x86_64-pc-windows-gnu'
      shell: bash
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add CHANGELOG.md
        git commit -m "docs: update changelog [skip ci]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}