name: 'Upload'
description: 'Upload to github releases'
inputs:
  github_token:
    description: 'github access token for upload artifact'
    required: true
  version:
    description: 'release version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Upload artifact to Github releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
          files: dist/admissibility-rust*
          repo_token: ${{ inputs.github_token }}
          automatic_release_tag: 'v${{ inputs.version }}'
          prerelease: false
