name: 'Upload'
description: 'Upload to github releases'
inputs:
  os:
    description: 'target os name'
    required: true
  github_token:
    description: 'github access token for upload artifact'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Upload artifact to Github releases
      uses: svenstaro/upload-release-action@v2
      with:
          name: binary-${{ input.os }}
          file: dist/admissibility-rust*
          repo_token: ${{ input.github_token }}
          tag: 'v${{ github.run_number }}'
          overwrite: true
          file_glob: true